# Services definition
services:
# MariaDB service
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        MYSQL_PORT: ${MYSQL_PORT:-3306}   # nimmt Wert aus .env oder Default 3306
    image: mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    secrets:
      - mysql_root_password
      - mysql_password

  # WordPress service

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      args:
        WP_FPM_PORT: ${WP_FPM_PORT:-9000}   # nimmt Wert aus .env oder Default 9000
    image: wordpress
    env_file: .env
    volumes:
      - wp_files:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    secrets:
      - wp_admin_password
      - wp_user_password
      - mysql_password

  # Nginx service

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    ports:
      - "${NGINX_PORT:-443}:${NGINX_INTERNAL_PORT:-443}"
    volumes:
      - wp_files:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

# Volumes definition

volumes:
  db_data:
    driver: local # Local driver
    driver_opts:
      type: none
      o: bind
      device: /home/mhummel/data/db # Bind host dir
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mhummel/data/wordpress

# Networks definition

networks:
  inception:
    driver: bridge # Custom bridge network

# Secrets definition
secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_password:
    file: ./secrets/mysql_password
  wp_admin_password:
    file: ./secrets/wp_admin_password
  wp_user_password:
    file: ./secrets/wp_user_password