
# Services definition
services:
# MariaDB service
  mariadb:
    container_name: mariadb # Container name
    build: requirements/mariadb # Build from Dockerfile in dir
    image: mariadb # name of the image
    env_file: .env # Load non-sensitive vars
    volumes:
      - db_data:/var/lib/mysql # Persistent DB data
    networks:
      - inception # Custom network
    restart: always # Auto-restart on fail
    secrets: # Load secrets
      - mysql_root_password
      - mysql_password

  # WordPress service

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wp_files:/var/www/wordpress # Persistent WP files
    networks:
      - inception
    depends_on:
      - mariadb # Start after DB
    restart: always
    secrets:
      - wp_admin_password
      - wp_user_password
      - mysql_password

  # Nginx service

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    ports:
      - "443:443" # Expose HTTPS only
    volumes:
      - wp_files:/var/www/wordpress # Share WP files
    networks:
      - inception
    depends_on:
      - wordpress # Start after WP
    restart: always

# Volumes definition

volumes:
  db_data:
    driver: local # Local driver
    driver_opts:
      type: none
      o: bind
      device: /home/mhummel/data/db # Bind host dir
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mhummel/data/wordpress

# Networks definition

networks:
  inception:
    driver: bridge # Custom bridge network

# Secrets definition
secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_password:
    file: ./secrets/mysql_password
  wp_admin_password:
    file: ./secrets/wp_admin_password
  wp_user_password:
    file: ./secrets/wp_user_password
